load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Google Test
http_archive(
  name = "googletest",
  sha256 = "755f9a39bc7205f5a0c428e920ddad092c33c8a1b46997def3f1d4a82aded6e1",
  urls = ["https://github.com/google/googletest/archive/5ab508a01f9eb089207ee87fd547d290da39d015.zip"],
  strip_prefix = "googletest-5ab508a01f9eb089207ee87fd547d290da39d015",
)

http_archive(
    name = "rules_python",
    sha256 = "497ca47374f48c8b067d786b512ac10a276211810f4a580178ee9b9ad139323a",
    strip_prefix = "rules_python-0.16.1",
    url = "https://github.com/bazelbuild/rules_python/archive/refs/tags/0.16.1.tar.gz",
)

# Project Generator
http_archive(
    name = "bzlmodrio-gentool",
    sha256 = "91dbeb541a6151eab3f4dfa37318b81e3f4fa964e45ebea48665cb2b3e471353",
    strip_prefix = "gentool-dummy_version",
    url = "https://github.com/bzlmodRio/gentool/archive/refs/heads/dummy_version.zip",
)

load("@rules_python//python:pip.bzl", "pip_parse")

pip_parse(
    name = "pip",
    requirements_lock = "@bzlmodrio-gentool//:requirements_lock.txt",
)


load("@pip//:requirements.bzl", "install_deps")
install_deps()

# Roborio Toolchain
http_archive(
    name = "rules_roborio_toolchain",
    sha256 = "6a92e62829905cdc8bdb398b5467476699dff503be3d0b49c122e9ed8c9df35f",
    strip_prefix = "rules_roborio_toolchain-836647310508c1c9a838adc12f0535ea6abdcff5",
    url = "https://github.com/bzlmodRio/rules_roborio_toolchain/archive/836647310508c1c9a838adc12f0535ea6abdcff5.zip",
)


load("@rules_roborio_toolchain//:maven_deps.bzl", "setup_legacy_setup_toolchains_dependencies")
setup_legacy_setup_toolchains_dependencies()

load("@rules_roborio_toolchain//toolchains:load_toolchains.bzl", "load_toolchains")
load_toolchains()

register_toolchains(
    "@local_roborio//:macos",
    "@local_roborio//:linux",
    "@local_roborio//:windows",
)

# Bazelrio Rules
local_repository(
    name = "rules_bazelrio",
    path = "../../bzlmodRio-rules_bazelrio",
)



# My repository!
local_repository(
    name = "bzlmodrio-ni",
    path = "../",
)

load("@bzlmodrio-ni//:maven_cpp_deps.bzl", "setup_legacy_bzlmodrio_ni_cpp_dependencies")
setup_legacy_bzlmodrio_ni_cpp_dependencies()

