load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Google Test
http_archive(
  name = "googletest",
  urls = ["https://github.com/google/googletest/archive/5ab508a01f9eb089207ee87fd547d290da39d015.zip"],
  strip_prefix = "googletest-5ab508a01f9eb089207ee87fd547d290da39d015",
)

# Roborio Toolchain
local_repository(
    name = "rules_roborio_toolchain",
    path = "../../rules_roborio_toolchain",
)


load("@rules_roborio_toolchain//:maven_deps.bzl", "setup_legacy_setup_toolchains_dependencies")
setup_legacy_setup_toolchains_dependencies()

load("@rules_roborio_toolchain//toolchains:load_toolchains.bzl", "load_toolchains")
load_toolchains()

register_toolchains(
    "@local_roborio//:cc-toolchain-roborio",
)

# Bazelrio Rules
local_repository(
    name = "rules_bazelrio",
    path = "../../bzlmodRio-rules_bazelrio",
)

# My repository!
local_repository(
    name = "bzlmodrio-ni",
    path = "../",
)

load("@bzlmodrio-ni//:maven_cpp_deps.bzl", "setup_legacy_bzlmodrio_ni_cpp_dependencies")
setup_legacy_bzlmodrio_ni_cpp_dependencies()

