load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Google Test
http_archive(
  name = "googletest",
  urls = ["https://github.com/google/googletest/archive/5ab508a01f9eb089207ee87fd547d290da39d015.zip"],
  strip_prefix = "googletest-5ab508a01f9eb089207ee87fd547d290da39d015",
)

http_archive(
    name = "rules_python",
    sha256 = "497ca47374f48c8b067d786b512ac10a276211810f4a580178ee9b9ad139323a",
    strip_prefix = "rules_python-0.16.1",
    url = "https://github.com/bazelbuild/rules_python/archive/refs/tags/0.16.1.tar.gz",
)

# Project Generator
local_repository(
    name = "bzlmodrio-gentool",
    path = "../../gentool",
)

load("@rules_python//python:pip.bzl", "pip_parse")

pip_parse(
    name = "pip",
    requirements_lock = "@bzlmodrio-gentool//:requirements_lock.txt",
)


load("@pip//:requirements.bzl", "install_deps")
install_deps()

# Roborio Toolchain
local_repository(
    name = "rules_roborio_toolchain",
    path = "../../rules_roborio_toolchain",
)


load("@rules_roborio_toolchain//:maven_deps.bzl", "setup_legacy_setup_toolchains_dependencies")
setup_legacy_setup_toolchains_dependencies()

load("@rules_roborio_toolchain//toolchains:load_toolchains.bzl", "load_toolchains")
load_toolchains()

register_toolchains(
    "@local_roborio//:cc-toolchain-roborio",
)

# Bazelrio Rules
local_repository(
    name = "rules_bazelrio",
    path = "../../bzlmodRio-rules_bazelrio",
)




# My repository!
local_repository(
    name = "bzlmodrio-ni",
    path = "../",
)

load("@bzlmodrio-ni//:maven_cpp_deps.bzl", "setup_legacy_bzlmodrio_ni_cpp_dependencies")
setup_legacy_bzlmodrio_ni_cpp_dependencies()
